# Generated by Django 5.1.4 on 2026-08-13 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('skripsi', 'Skripsi'), ('sidang', 'Sidang'), ('wisuda', 'Wisuda'), ('camping', 'Camping')], max_length=50)),
                ('nim', models.CharField(max_length=20, verbose_name='NIM')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('thesis_title', models.CharField(blank=True, max_length=500, null=True)),
                ('advisor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_year', models.CharField(blank=True, help_text="e.g., '2023/2024'", max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ticket_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.studyprogram')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('nik', models.CharField(max_length=16, unique=True, verbose_name='NIK')),
                ('birth_place', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('religion', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('previous_school', models.CharField(max_length=255)),
                ('graduation_year', models.CharField(max_length=4)),
                ('previous_major', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_occupation', models.CharField(max_length=255)),
                ('parent_income', models.CharField(help_text="e.g., '< 1 Juta', '1-3 Juta'", max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chosen_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.studyprogram')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TracerStudySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True, verbose_name='NIM')),
                ('full_name', models.CharField(max_length=255)),
                ('graduation_year', models.CharField(max_length=4)),
                ('employment_status', models.CharField(choices=[('Bekerja', 'Bekerja'), ('Wirausaha', 'Wirausaha'), ('Lanjut Studi', 'Lanjut Studi'), ('Mencari Kerja', 'Mencari Kerja')], max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('first_job_time_months', models.IntegerField(blank=True, help_text='Time to get first job in months', null=True)),
                ('monthly_salary_range', models.CharField(blank=True, help_text="e.g., '3-5 Juta'", max_length=100, null=True)),
                ('relevance_to_major', models.CharField(choices=[('Sangat Sesuai', 'Sangat Sesuai'), ('Sesuai', 'Sesuai'), ('Kurang Sesuai', 'Kurang Sesuai'), ('Tidak Sesuai', 'Tidak Sesuai')], max_length=50)),
                ('feedback_for_campus', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.studyprogram')),
            ],
            options={
                'verbose_name_plural': 'Tracer Study Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
