# Generated by Django 5.1.4 on 2026-08-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_count', models.IntegerField()),
                ('alumni_count', models.IntegerField()),
                ('study_programs_count', models.IntegerField()),
                ('employed_rate_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('accreditation_grade', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Campus Stats',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pmb_email', models.EmailField(max_length=254)),
                ('operational_hours', models.TextField()),
                ('google_maps_embed_url', models.URLField()),
                ('instagram', models.CharField(default='', max_length=255)),
                ('facebook', models.CharField(default='', max_length=255)),
                ('youtube', models.CharField(default='', max_length=255)),
                ('tiktok', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='hero/')),
                ('cta_text', models.CharField(max_length=100)),
                ('cta_link', models.CharField(max_length=500)),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PopupAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='popup/')),
                ('description', models.TextField()),
                ('cta_text', models.CharField(max_length=100)),
                ('cta_link', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RectorGreeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='rector/')),
                ('quote', models.TextField()),
                ('full_message', models.JSONField(default=list, help_text='List of paragraphs')),
            ],
            options={
                'verbose_name_plural': 'Rector Greeting',
            },
        ),
    ]
