# Generated by Django 5.1.4 on 2026-08-21 02:00

import config.image_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Wajib 1920 x 720 px, JPG/PNG/WebP. Rasio 8:3.', upload_to='hero/', validators=[config.image_validation.validate_hero_image]),
        ),
        migrations.AlterField(
            model_name='popupannouncement',
            name='image',
            field=models.ImageField(help_text='Wajib 1200 x 800 px, JPG/PNG/WebP. Rasio 3:2.', upload_to='popup/', validators=[config.image_validation.validate_popup_image]),
        ),
        migrations.AlterField(
            model_name='rectorgreeting',
            name='photo',
            field=models.ImageField(help_text='Wajib 600 x 800 px, JPG/PNG/WebP. Foto portrait 3:4.', upload_to='rector/', validators=[config.image_validation.validate_rector_photo]),
        ),
    ]
