# Generated by Django 5.1.4 on 2026-08-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_heroslide_image_alter_popupannouncement_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RunningQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VideoTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_embed_url', models.URLField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Video Tour',
            },
        ),
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField()),
                ('missions', models.JSONField(default=list, help_text='List of mission point strings')),
            ],
            options={
                'verbose_name_plural': 'Vision Mission',
            },
        ),
    ]
