# Generated by Django 5.1.4 on 2026-08-13 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('Institusi', 'Institusi'), ('Program Studi', 'Program Studi')], max_length=50)),
                ('accreditation_grade', models.CharField(choices=[('Unggul', 'Unggul'), ('Baik Sekali', 'Baik Sekali'), ('Baik', 'Baik'), ('A', 'A'), ('B', 'B')], max_length=50)),
                ('decree_number', models.CharField(help_text='No SK BAN-PT / LAM-PTKes', max_length=255)),
                ('valid_until', models.DateField()),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='accreditation/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('dean_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='faculty/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('degree', models.CharField(choices=[('D3', 'D3'), ('S1', 'S1'), ('Profesi', 'Profesi'), ('S2', 'S2')], max_length=20)),
                ('accreditation', models.CharField(choices=[('Unggul', 'Unggul'), ('Baik Sekali', 'Baik Sekali'), ('Baik', 'Baik'), ('A', 'A'), ('B', 'B')], max_length=50)),
                ('content', models.TextField()),
                ('duration_years', models.IntegerField()),
                ('career_outlooks', models.JSONField(default=list, help_text='List of career outlooks')),
                ('head_of_program', models.CharField(max_length=255)),
                ('icon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.faculty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
