# Generated by Django 5.1.4 on 2026-08-21 02:00

import config.image_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation',
            name='image',
            field=models.ImageField(help_text='Wajib 1200 x 800 px, JPG/PNG/WebP. Rasio 3:2.', upload_to='accreditation/', validators=[config.image_validation.validate_accreditation_image]),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(help_text='Wajib 800 x 500 px, JPG/PNG/WebP. Rasio 8:5.', upload_to='faculty/', validators=[config.image_validation.validate_faculty_image]),
        ),
    ]
