# Generated by Django 5.1.4 on 2026-08-13 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GuidelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('target_audience', models.CharField(choices=[('Mahasiswa', 'Mahasiswa'), ('Dosen & Staff', 'Dosen & Staff'), ('Umum', 'Umum')], max_length=50)),
                ('file_size', models.CharField(help_text="e.g., '1.2 MB'", max_length=50)),
                ('file_type', models.CharField(default='PDF', help_text='Currently PDF only', max_length=10)),
                ('download_url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Guideline Items',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('field', models.CharField(choices=[('Keperawatan', 'Keperawatan'), ('Kebidanan', 'Kebidanan'), ('Farmasi', 'Farmasi'), ('Teknologi Informasi', 'Teknologi Informasi'), ('Manajemen Rumah Sakit', 'Manajemen Rumah Sakit'), ('Umum', 'Umum')], max_length=50)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(default=list, help_text='List of requirements')),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('image', models.ImageField(upload_to='jobs/')),
                ('is_published', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-close_date'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('KIP-Kuliah', 'KIP-Kuliah'), ('Yayasan Ichsan Satya', 'Yayasan Ichsan Satya'), ('Pemerintah Daerah', 'Pemerintah Daerah'), ('Mitra Industri', 'Mitra Industri')], max_length=100)),
                ('image', models.ImageField(upload_to='scholarships/')),
                ('summary', models.TextField()),
                ('eligibility', models.JSONField(default=list, help_text='List of eligibility criteria')),
                ('benefits', models.JSONField(default=list, help_text='List of benefits')),
                ('deadline', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('graduate_year', models.CharField(max_length=4)),
                ('program_name', models.CharField(max_length=255)),
                ('current_job', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('quote', models.TextField()),
                ('photo', models.ImageField(upload_to='testimonials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='training/')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('registration_link', models.URLField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past')], max_length=20)),
                ('fee', models.CharField(max_length=100)),
                ('quota_left', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_size', models.CharField(help_text="e.g., '2.5 MB'", max_length=50)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('XLSX', 'XLSX')], max_length=20)),
                ('download_url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='programs_public.documentcategory')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='speakers/')),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='programs_public.training')),
            ],
        ),
    ]
