# Generated by Django 5.1.4 on 2026-08-21 02:00

import config.image_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs_public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='image',
            field=models.ImageField(help_text='Wajib 1200 x 800 px, JPG/PNG/WebP. Rasio 3:2.', upload_to='jobs/', validators=[config.image_validation.validate_card_image]),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='image',
            field=models.ImageField(help_text='Wajib 1200 x 800 px, JPG/PNG/WebP. Rasio 3:2.', upload_to='scholarships/', validators=[config.image_validation.validate_card_image]),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(help_text='Wajib 600 x 600 px, JPG/PNG/WebP. Foto square 1:1.', upload_to='speakers/', validators=[config.image_validation.validate_square_photo]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(help_text='Wajib 600 x 600 px, JPG/PNG/WebP. Foto square 1:1.', upload_to='testimonials/', validators=[config.image_validation.validate_square_photo]),
        ),
        migrations.AlterField(
            model_name='training',
            name='image',
            field=models.ImageField(help_text='Wajib 1200 x 675 px, JPG/PNG/WebP. Rasio 16:9.', upload_to='training/', validators=[config.image_validation.validate_training_image]),
        ),
    ]
