# Generated by Django 5.1.4 on 2026-08-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Penelitian', 'Penelitian'), ('Pengabdian Masyarakat', 'Pengabdian Masyarakat'), ('Jurnal & Publikasi', 'Jurnal & Publikasi')], max_length=50)),
                ('author', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('cover_image', models.ImageField(upload_to='research/')),
                ('abstract', models.TextField()),
                ('content', models.TextField(help_text='Rich text/HTML content')),
                ('download_pdf_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Akademik', 'Akademik'), ('Pengumuman', 'Pengumuman'), ('Prestasi', 'Prestasi'), ('Kegiatan', 'Kegiatan'), ('Penelitian', 'Penelitian')], max_length=50)),
                ('cover_image', models.ImageField(upload_to='news/')),
                ('published_at', models.DateTimeField(db_index=True)),
                ('author', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('content', models.TextField(help_text='Rich text/HTML content')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_news_publish_ad4867_idx'), models.Index(fields=['category', '-published_at'], name='news_news_categor_83f27b_idx')],
            },
        ),
    ]
