# Generated by Django 5.1.4 on 2026-08-21 02:00

import config.image_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(help_text='Wajib 1200 x 675 px, JPG/PNG/WebP. Rasio 16:9.', upload_to='news/', validators=[config.image_validation.validate_news_image]),
        ),
        migrations.AlterField(
            model_name='researchnews',
            name='cover_image',
            field=models.ImageField(help_text='Wajib 1200 x 675 px, JPG/PNG/WebP. Rasio 16:9.', upload_to='research/', validators=[config.image_validation.validate_news_image]),
        ),
    ]
